require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PushOffersController do

  # This should return the minimal set of attributes required to create a valid
  # PushOffer. As you add validations to PushOffer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PushOffersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all push_offers as @push_offers" do
      push_offer = PushOffer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:push_offers).should eq([push_offer])
    end
  end

  describe "GET show" do
    it "assigns the requested push_offer as @push_offer" do
      push_offer = PushOffer.create! valid_attributes
      get :show, {:id => push_offer.to_param}, valid_session
      assigns(:push_offer).should eq(push_offer)
    end
  end

  describe "GET new" do
    it "assigns a new push_offer as @push_offer" do
      get :new, {}, valid_session
      assigns(:push_offer).should be_a_new(PushOffer)
    end
  end

  describe "GET edit" do
    it "assigns the requested push_offer as @push_offer" do
      push_offer = PushOffer.create! valid_attributes
      get :edit, {:id => push_offer.to_param}, valid_session
      assigns(:push_offer).should eq(push_offer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PushOffer" do
        expect {
          post :create, {:push_offer => valid_attributes}, valid_session
        }.to change(PushOffer, :count).by(1)
      end

      it "assigns a newly created push_offer as @push_offer" do
        post :create, {:push_offer => valid_attributes}, valid_session
        assigns(:push_offer).should be_a(PushOffer)
        assigns(:push_offer).should be_persisted
      end

      it "redirects to the created push_offer" do
        post :create, {:push_offer => valid_attributes}, valid_session
        response.should redirect_to(PushOffer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved push_offer as @push_offer" do
        # Trigger the behavior that occurs when invalid params are submitted
        PushOffer.any_instance.stub(:save).and_return(false)
        post :create, {:push_offer => {  }}, valid_session
        assigns(:push_offer).should be_a_new(PushOffer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PushOffer.any_instance.stub(:save).and_return(false)
        post :create, {:push_offer => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested push_offer" do
        push_offer = PushOffer.create! valid_attributes
        # Assuming there are no other push_offers in the database, this
        # specifies that the PushOffer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PushOffer.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => push_offer.to_param, :push_offer => { "these" => "params" }}, valid_session
      end

      it "assigns the requested push_offer as @push_offer" do
        push_offer = PushOffer.create! valid_attributes
        put :update, {:id => push_offer.to_param, :push_offer => valid_attributes}, valid_session
        assigns(:push_offer).should eq(push_offer)
      end

      it "redirects to the push_offer" do
        push_offer = PushOffer.create! valid_attributes
        put :update, {:id => push_offer.to_param, :push_offer => valid_attributes}, valid_session
        response.should redirect_to(push_offer)
      end
    end

    describe "with invalid params" do
      it "assigns the push_offer as @push_offer" do
        push_offer = PushOffer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PushOffer.any_instance.stub(:save).and_return(false)
        put :update, {:id => push_offer.to_param, :push_offer => {  }}, valid_session
        assigns(:push_offer).should eq(push_offer)
      end

      it "re-renders the 'edit' template" do
        push_offer = PushOffer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PushOffer.any_instance.stub(:save).and_return(false)
        put :update, {:id => push_offer.to_param, :push_offer => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested push_offer" do
      push_offer = PushOffer.create! valid_attributes
      expect {
        delete :destroy, {:id => push_offer.to_param}, valid_session
      }.to change(PushOffer, :count).by(-1)
    end

    it "redirects to the push_offers list" do
      push_offer = PushOffer.create! valid_attributes
      delete :destroy, {:id => push_offer.to_param}, valid_session
      response.should redirect_to(push_offers_url)
    end
  end

end
